### ISSUE TITLE
Feature request: word wrap option in text edit mode

### ISSUE THREAD

**Issue by AaronOldenburg** [MicroPad/MicroPad-Electron#31] opened 2019-10-27 15:41 UTC
I would like the option, when I'm typing notes, to constrain what I'm typing to the width I have the window at, instead of going on to the right. It wraps the text nicely when I exit out of edit mode, I'd just like it to wrap in edit mode as well, since I spend so much time there.

**Comment by NickGeek** [comment] 2019-10-28 07:54
I'm closing this as a duplicate of https://github.com/MicroPad/Web/issues/193 but yes, I agree.

Until a change can be made I'd recommend hitting "enter" to wrap, one new line won't effect any of the output (markdown will only do a new paragraph on two enters or a double-space newline).

**Closed as completed by NickGeek** 2019-10-28 07:54 UTC
Labels: duplicate
